# Generated by Django 3.1 on 2020-08-30 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='expired',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
